# Generated by Django 4.0.4 on 2024-02-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Ф.И.О')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('delivery_address', models.CharField(max_length=255, null=True)),
                ('recipe', models.FileField(null=True, upload_to='recipe_photos/', verbose_name='Рецепт')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('payment_method', models.CharField(blank=True, choices=[('kaspi', 'Выставить счет в Kaspi'), ('card', 'Банковская карта'), ('cash', 'Наличными курьеру')], max_length=20, null=True, verbose_name='Способ оплаты')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата заказа')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая сумма')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('accepted', 'Принят'), ('canceled', 'Отменен'), ('done', 'Доставлен')], default='processing', max_length=20, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название производителя')),
                ('description', models.TextField(verbose_name='Описание производителя')),
                ('photo', models.FileField(upload_to='photos/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('article', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул товара')),
                ('photo', models.FileField(upload_to='product_photos/', verbose_name='Фото товара')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание товара')),
                ('instruction', models.FileField(blank=True, null=True, upload_to='instructions/', verbose_name='Инструкция по использованию')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('recipe_required', models.BooleanField(default=False, verbose_name='Требуется рецепт')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категория')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.producer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('stars', models.PositiveIntegerField(default=5, verbose_name='Оценка')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product')),
            ],
            options={
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.product')),
            ],
            options={
                'verbose_name_plural': 'Компонент корзины',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='project.CartProduct', to='project.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('photo', models.FileField(upload_to='adv/', verbose_name='Фото товара')),
                ('date', models.DateField(verbose_name='Дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
